apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-local-pv
