apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-nfs-pv
