apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wp-nfs-pv
