apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsshare
    server: nfs-service.default.svc.cluster.local
  persistentVolumeReclaimPolicy: Retain
