apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-local-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: wp-local-pv
